sudo: required
services:
  - docker

before_install:
  - docker build -t estvii/react-pics -f Dockerfile.dev .
  # - docker build -t estvii/react-pics .

script: 
  - docker run estvii/react-pics npm run test -- --coverage && npm install && npm run build
  # - docker run estvii/react-pics
# after_success:
  

deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY  
  bucket: "react-pics"
  skip_cleanup: true
  region: "us-east-1"
  local_dir: build