sudo: required
services:
  - docker

before_install:
  # - docker build -t estvii/react-pics -f Dockerfile.dev .

script: 
  # - docker run estvii/react-pics npm run test -- --coverage

before_deploy:
  pip install --user awscli
  script: 
    npm run build

deploy:
  on:
    branch: master
  provider: script
  script: ~/.local/bin/aws s3 sync build s3://react-pics
  skip_cleanup: true
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY  
