sudo: required
services:
  - docker

before_install:
  - docker build -t estvii/react-pics -f Dockerfile.dev .

script: 
  - docker run estvii/react-pics npm run test -- --coverage

deploy:
  skip_cleanup: true
  on:
    branch: master
  provider: s3
  region: us-east-1
  bucket: "react-pics"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: build
